os: linux
dist: xenial
language: python

python: 3.8

jobs:
  fast_finish: true
  include:
    - stage: deploy
      python: 3.8
      if: tag IS present
      deploy:
        provider: pypi
        user: "__token__"
        # password: see secret PYPI_PASSWORD variable
        distributions: sdist bdist_wheel
        on:
          tags: true